volumes:
  postgres-data:

services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./data:/app/data
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
